---
title: "Reporte sobre análisis de protestas sociales en Sudamérica"
author: "Jorge San Martín"
format: html
editor: visual
self-contained: true
---

## Introducción

Durante el año 2019, Chile se vió inmerso en una serie de masivas y violentas protestas a nivel nacional que conmocionaron al país, teniendo importantes consecuencias a nivel político y social; situación que acabó por denominarse "Estallido social". Sin embargo, Chile no fue el único país latinoamericano envuelto en masivas protestas durante los últimos años. También experimentaron estallidos países como Ecuador el 2019, Colombia el 2019-2020, Perú el 2020, entre otros. Esto nos indica que las masivas protestas sociales del último tiempo ha sido un fenómeno que ha permeado el subcontinente latinoamericano.

Sin embargo, este fenómeno no ha sido homogéneo en los distintos países involucrados; hay diferencias remarcables, como la masividad, duración temporal y la violencia de estas protestas, que pueden ser de interés para futuros análisis de carácter sociológico, político, económico, etc... Es debido a esto el posible valor de analizar las características que diferencian estos fenómenos de masivas protestas en sudamérica en los últimos cuatro años.

Este trabajo está basado principlamente en el trabajo realizado por el proyecto *Armed Conflict Location & Event Data Project* (ACLED) que recopila información sobre fechas, actores, lugares, muertes y todo tipo de eventos de violencia y protesta política en todo el mundo. El reporte busca analizar cuantitativamente, entre países, las diferencias en la cantidad de manifestaciones, su duración temporal y sus niveles de violencia, para armar un panorama general y específico sobre el fenómeno de las masivas protestas sociales de los últimos años.

Debido al tamaño y complejidad de esta tarea, y de la completa base de datos que entrega ACLED, por simplicidad se trabajó en este reporte con los datos sobre manifestaciones basados en países de Sudamérica. Las variables analizadas corresponden a: fecha de la manifestación, mes y año, desde el año 2018 hasta el 2022; tipo de evento, *riots* (disturbios) y *protests* para manifestaciones violentas y no violentas respectivamente; y cantidad de muertos en la manifestación como medida de violencia. En las siguientes secciones se encuentran el Desarrollo donde está el grueso del analísis con sus correspondientes resultados en gráficos de los datos, y la Conclusión que entrega las últimas reflexiones extraídas a partir de la información obtenida.
